// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace animalshelterapi.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20200612154723_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Breed");

                    b.Property<string>("Details");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Breed = "Mutt Tabby Cat",
                            Details = "Cute, but wild. Tends to bite a lot",
                            Name = "Charlie"
                        },
                        new
                        {
                            AnimalId = 2,
                            Breed = "Mutt Tabby Cat",
                            Details = "Very sweet, overall good cat.",
                            Name = "Mochi"
                        },
                        new
                        {
                            AnimalId = 3,
                            Breed = "Mutt Black and White Cat",
                            Details = "Very independent cat. ",
                            Name = "Kenji"
                        },
                        new
                        {
                            AnimalId = 4,
                            Breed = "All Grey Cat",
                            Details = "Lap cat, always needs affection.",
                            Name = "Sumo"
                        },
                        new
                        {
                            AnimalId = 5,
                            Breed = "German Shepard",
                            Details = "Medium size dog, can be walked without leash.",
                            Name = "Honda"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
